# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "boxcutter/ubuntu1404"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    v.customize ["modifyvm", :id, "--memory", 512]
  end

  config.vm.define "apache" do |apache|
    apache.vm.hostname = "passenger-apache"
    apache.vm.network :forwarded_port, guest: 80, host: 8080
    apache.vm.network :private_network, ip: "10.0.0.10"

    apache.vm.provision :ansible do |ansible|
      ansible.playbook = "apache/apache.yml"
      ansible.verbose = false
    end
  end

 config.vm.define "nginx" do |nginx|
    nginx.vm.hostname = "passenger-nginx"
    nginx.vm.network :forwarded_port, guest: 80, host: 8081
    nginx.vm.network :private_network, ip: "10.0.0.11"

    nginx.vm.provision :ansible do |ansible|
      ansible.playbook = "nginx/nginx.yml"
      ansible.verbose = false
    end
  end

 config.vm.define "standalone" do |standalone|
    standalone.vm.hostname = "passenger-standalone"
    standalone.vm.network :forwarded_port, guest: 80, host: 8083
    standalone.vm.network :private_network, ip: "10.0.0.12"

    standalone.vm.provision :ansible do |ansible|
      ansible.playbook = "standalone/standalone.yml"
      ansible.verbose = false
    end
  end

end
